config/routes.rb
Rails.application.routes.draw do
	get 'users/new'
	get 'users/login'
	
	get 'users/signup'
	get 'welcome/index'
	post 'users/users_login'
	root 'welcome#index'
	resources :users
	get 'logout', to: 'users#logout'
	# match ':controller(/:action(/:id))(.:format)'
	
	# match ':controller(/:action(/:id))(.:format)'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	# validate :password_complexity
 #  validate :email_require
  # validates :first_name, :last_name, :dob, :email, :mobile, presence: true
  before_save :encrypt_password1
  after_save :clear_password

# def password_complexity
#   return if encrypted_password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,20}$/
#   errors.add :password, 'Complexity requirement not met. Length should be 6-20 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
# end

# def email_require
#   return if email.blank? || email =~ /@./
#   errors.add :email, 'Email should have @ or .'
# end


def encrypt_password1
  if encrypted_password.present?
     salt = BCrypt::Engine.generate_salt
     self.encrypted_password= BCrypt::Engine.hash_secret(encrypted_password, salt)
  end
 end
 
 def clear_password
  self.encrypted_password = nil
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# protected 

# def authenticate_user
#   if session[:user_id]
#     @current_user = User.find session[:user_id] 
#     return true	
#   else
#     redirect_to users_path
#     return false
#   end
# end
# def save_login_state
#   if session[:user_id]
#     redirect_to users_login_path
#     return false
#   else
#     return true
#   end
# end

 # chandniverma11@gmail.com
 # Chandni
 # 8989



	
	# n@nn
	# nnn
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :check_session, :only => [:index, :show]
before_action :check_session_for_login, :only => [:login, :signup]
# validates :first_name, :last_name, :email, :encrypted_password : true

# before_filter :save_login_state, :only => [:users_login]
  
   def index
    @users = User.all
   end

   def new
     @user =Users.new
   end

   def show
    @user = User.find_by_id(params[:id])
    # redirect_to users_path if @user.nil?
   end

   def users_login
     @user = User.find_by_email(params[:email])
      if @user.present?
      if (@user.encrypted_password == params[:encrypted_password])
          session[:user_id] = @user.id
          # if session.present?
            
          # flash[:notice] = "Wow Welcome again, you logged in"
          redirect_to users_path
        # if user && user.authenticate(params[:password])  
            
      elsif (@user.encrypted_password != params[:encrypted_password])
        
      else
         
      end 
    end
  end

  def login
  end

    
  def create
      @user = User.new(user_params)
      if @user.save
      # if user && user.authenticate(params[:password])  
      #    session[:user_id] = @user.id   
      #    redirect_to user_path(@user), notice: 'User successfully created.'   
      redirect_to user_path(@user)
      else
         render "new"
     end
  end

  def check_session
    unless session[:user_id].present?
      redirect_to users_login_path
    end
  end

  def check_session_for_login
    if session[:user_id].present?
      redirect_to users_path
    end
  end

  def logout
    session[:user_id] = nil   
    redirect_to users_login_path, notice: 'Logged out!'   
  end


  def signup
  end

   
  

     # def match_password(login_password="")
     # encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
     # end

    # def encrypt_password
    #  if password.present?
    #  self.salt = BCrypt::Engine.generate_salt
    #   self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    #  end
    # end

   # def clear_password
   #  self.password = nil
   # end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password )
    end
end

   

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyUser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        
    <%= yield %>
  </body>
</html>

app/views/layouts/extra.html.erb
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  <%= form_with scope: :user, url: users_path, local: true do |form| %>
<%= form_for :user, @user, :url => { :action => "index" } do |f| %>

<%= form_for(:user, :url =>  users_path), method: :get do |f| %>
<%= form_for @comment, url: article_comment_path(@article, @comment), method: :put do |form| %> 
<%= form_with scope: :user, url: users_path, local: true do |form| %>


<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<center>
   <h1> Welcome to dashboard </h1>
 </center>
<p style="text-align: right; font-size: 20px;">
  <%= link_to 'Logout', users_path %>
<table>
  <tr>
    <h3><th>First Name</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Last Name</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Email</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Password</th></h3>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.last_name %></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.email %></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.encrypted_password %></td>

      <td><%= link_to 'Show', article_path(user) %></td>
      <td><br></td>
      <td><br></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><br></td>
      <td><br></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>
</body>
</html>


<%= form_for @user, url: users_path(@user), method: :put do |form| %>


<%= text_field_tag :email%>
<%= text_field_tag :encrypted_password  %>

app/views/users/_form.html.erb
 <%= form_tag(edit_user_path, :method => "get") do %>
  <p>
    <%= form.label :first_name, "First Name:" %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name, "Last Name:" %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :email, "Email id:" %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :encryted_password, "Password:" %><br>
    <%= form.text_field :encryted_password %>
  </p>
 
  <p>
    <%= form.submit("Create")%>
  </p>
 
<% end %>



<!-- show page -->

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_tag(edit_user_path, :method => "get") do %>
  <p>
    <%= form.label :first_name, "First Name:" %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name, "Last Name:" %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :email, "Email id:" %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :encrypted_password, "Password:" %><br>
    <%= form.text_field :encrypted_password %>
  </p>
 
  <p>
    <%= form.submit("Update")%>
  </p>
 
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<center>
  <h1>Welcome to dashboard </h1>

<p style="text-align: right; font-size: 20px;">
  <%= link_to 'Logout', logout_path %>
</p>

<table>
  <tr>
    <h3><th>First Name</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Last Name</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Email</th></h3>
    <th><br></th>
    <th><br></th>
    <h3><th>Password</th></h3>
    <th><br></th>
    <th><br></th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.last_name%></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.email %></td>
      <td><br></td>
      <td><br></td>
      <td><%= user.encrypted_password %></td>
      <td><br></td>
      <td><br></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><br></td>
      <td><br></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><br></td>
      <td><br></td>
    <% end %>
</table>
<br>
</center>

app/views/users/login.html.erb
<!DOCTYPE>
<html>
<head>
	<title></title>
</head>
<body style="background-image: url(aa.jpg); height: 50; width: 50; background-repeat; ">
<%= form_tag(users_users_login_path, :method => "post") do %>

	<center>
		<h1>Login Form</h1>
		<table>

			<p>
			   <%= label_tag :email%><br>
			   <%= text_field_tag :email%>
			</p>
			<p>
				<%= label_tag :encrypted_password, 'Password'%><br>
				<%= password_field_tag :encrypted_password  %>
			</p>
			<p>
				<%= submit_tag "Login" %> 
				<h5>No account yet? <%= link_to 'Create an account', users_signup_path %></h5>
			</p>
		</table>
      <% end %> 
    </center>
	</html>

app/views/users/new.html.erb
<h1>New User</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE>
<html>
<head>
	<title></title>
</head>
<body style="background-image: url(aa.jpg); height: 50; width: 50; background-repeat; ">
<center>
    <h3>User Detail</h3>
    <p style="text-align: right; font-size: 20px;">
  <%= link_to 'Logout', logout_path %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.encrypted_password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |<!-- edit page -->
<%= link_to 'Back', users_signup_path %> <!-- index page -->
</center>
</body>
</html>

app/views/users/signup.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body style="background-image: url(aa.jpg); height: 50; width: 50; background-repeat; ">
<center>	
  <h1>Create an account</h1>
     <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

      <p> 
	     First Name:</br> <%= f.text_field :first_name%> 
       </p>

       <p> 
        Last Name:</br> <%= f.text_field :last_name%>
       </p>

       <p> 
	   Email:
       </br> <%= f.email_field :email%>
       </p>

       <p> 
	   Password:
      </br> <%= f.password_field :encrypted_password %>
      </p>

      <p> 
	   <%= f.submit :Signup %>
	   <% end %>
	  </p>
</center>
</body>
</html>

app/views/users/users_login.html.erb
<!DOCTYPE>
<html>
<head>
	<title></title>
</head>
<body style="background-image: url(aa.jpg); height: 50; width: 50; background-repeat; ">
<center>
    <h3>User Detail</h3>
    <p style="text-align: right; font-size: 20px;">
  <%= link_to 'Logout', logout_path %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.encrypted_password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |<!-- edit page -->
<%= link_to 'Back', users_signup_path %> <!-- index page -->
</center>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE>
	<html>
		<head>
			<title></title>
		</head>
		<body style="background-image: url(aa.jpg); height: 50; width: 50; background-repeat; ">
		</html>
			<center><h1>Welcome To User Application</h1></center>
			<br>
			<center><h3><%= link_to 'User Login', users_login_path %></h3>
			</div>
			<br>
			<br>
			<br>
			<h3><%= link_to 'User Signup', users_signup_path %></h3>
		</div>
	</center>
</body>